### ISSUE TITLE
Allow defaulting "Pass" filter to disabled/unchecked when there are failing tests?

### ISSUE THREAD

**Issue by wickkidd** [dkelosky/jest-stare#122]
When there are failing tests the passing test output is simply noise as I need to get to the failing test output so I can see what I need to correct. I took a look at the code for the "Switch" but I'm not sure what approach you would take given the way this is coded so I was hesitant to create a PR. If this enhancement is something you're open to, I'd be willing to create a PR, but I'd need to know what kind of approach you would want.

At a minimum I would think that this could be a config setting. Also, query params come to mind which would allow the burden of deciding when to set a `Switch` state to off to rest with the consumer. Thoughts?

**Comment by dkelosky** [comment]
Good points.  I'm definitely open and appreciate all contributions.  

The config approach seems most natural but query parms are an interesting idea.  The config is a little messy since introducing a new one means an update in like 4 places 😞 .

However, I'm a little indifferent on how it's done - since you're the first requestor - I think you can decide the externals.  If it's backwards compatible and has tests - I'll approve it 😄 

Thanks

**Comment by wickkidd** [comment]
Works. For those who stumble upon this, here's how I used it in a script that runs on our CI server in a catch block when tests fail:
![image](https://user-images.githubusercontent.com/5916/62387198-fa590200-b527-11e9-81eb-b8bf43ed135e.png)

Note: the json results file [_must_ be a jest-stare compatible one](https://github.com/dkelosky/jest-stare/issues/45#issuecomment-445467215). Since I have jest-stare as a reporter, it already ran once creating `jest-results.json` inside the jest-stare folder. I simply feed that file back to jest-stare programmatically and now the report is overwritten with one that has the passing tests hidden.

When tests pass, it simply uses jest-stare as a reporter:
![image](https://user-images.githubusercontent.com/5916/62387284-296f7380-b528-11e9-82c9-407da2faf582.png)
