### ISSUE TITLE
Report generates in default location

### ISSUE THREAD

**Issue by mastrodaro** [dkelosky/jest-stare#178]
Hey,

  one of last updates allowed to config via. jest config file. For this config:

```
reporters: [
    "default",
    [
      "jest-stare",
      {
        resultDir: "tests/unit/results",
        reportTitle: "...Test results",
        reportHeadline: "...",
        coverageLink: "../../coverage/index.html"
      }
    ],
```

I am getting two reports: one in under **/tests/unit/results** and second **/jest-stare**

**Comment by dkelosky** [comment]
Thanks for reporting.  So far, I haven't been able to reproduce.  What platform are you running on?  Also, maybe any messages that say `writing to` those locations.

**Comment by mastrodaro** [comment]
Windows, node: v10.16.0, npm: 6.9.0. I can check linux later.

Using with vue, cli config for jest unit testing.

**  jest-stare --testResultsProcessor: wrote output report to ./jest-stare/index.html   **

**Comment by dkelosky** [comment]
Thank you - that makes a lot of sense.  The `testResultsProcessor` runs at the end and can only read config from the `jest-stare` config in package json since `[testResultsProcessor](https://jestjs.io/docs/en/configuration.html#testresultsprocessor-string)` do not allow passing a config.

Some projects document that `testResultsProcessor` will be deprecated, but I can't find information on that.  

Sorry for the troubles, I'll have to document this configuration limitation in the README.  I'll leave this open until then.
