### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [dkelosky/jest-stare#285]
I just saw the package is updated to `v2.0.0`, but I can't find any CHANGELOG to check out the changes.

Would you be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work @dkelosky! 🙂

**Comment by dkelosky** [comment]
Good point - it was an oversight.  Most enhancements are coming from contributors - I get the boring task of maintaining currency.  For the next enhancement I'll be sure to add a changelog.  

For completeness, `v2.0.0` was a major version bump because the UI changed with this PR: https://github.com/dkelosky/jest-stare/pull/272
