### ISSUE TITLE
Question: ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by jellypuno** [dkelosky/jest-stare#307]
![Capture](https://user-images.githubusercontent.com/45042840/82811845-f8cf4080-9e91-11ea-9925-0e834b78fc31.PNG)

I am having this error when I run my unit test. As I understand correctly, it is an error when using fs? I am not sure. Maybe it is just me and I am missing some modules.

**Comment by dkelosky** [comment]
I think this is another reporter failing.  Are there some steps I can use to reproduce this?

**Comment by jellypuno** [comment]
it happens whenever I click npm run:test in Zowe Explorer

**Comment by dkelosky** [comment]
I'll pull it and give it a shot.  Thank you

**Comment by dkelosky** [comment]
Is it just `npm run test` in on the `master` branch?  Is it the `unit` tests?  I'm unable to reproduce this.

**Comment by jellypuno** [comment]
I am running `npm run test:unit` on master branch. I recently re-imaged my PC. Do you think the error can happen because of that?

**Comment by dkelosky** [comment]
I'm trying a few different scenarios but am unable to reproduce.  I'd like to get to the bottom of this though because last time we found that mocking issue.

Is there anything else special about your environment besides reimaging your machine?  Is anyone else getting this error?   

I think something else is failing though, after this line, `jest-stare` no longer has control:
![image](https://user-images.githubusercontent.com/14940561/83256980-75f40180-a181-11ea-9621-8b69baa17134.png)

**Comment by jellypuno** [comment]
hmm. I don't know. At first I was thinking, maybe because i'm using VSCode Insiders but I ran the test in regular VSCode and the error is still there:

![Capture](https://user-images.githubusercontent.com/45042840/83257785-5bd41680-a1b5-11ea-9bce-38c1d5af2364.PNG)

**Comment by dkelosky** [comment]
Are you running Node.js 14 by chance?

**Comment by jellypuno** [comment]
aha! yes I am :) do you think that's the culprit?

**Comment by dkelosky** [comment]
i think so - it looks like `graceful-fs` may be failing the same way [this project is](https://github.com/fivdi/onoff/issues/170) under the Node 14 changes

**Comment by jellypuno** [comment]
I see. So no issues then 😄 Thank you for investigating it.

**Comment by dkelosky** [comment]
Thanks @jellypuno - Ok to close?

**Comment by jellypuno** [comment]
yes. Go for it 😉
